In [ ]:
import pandas as pd
import numpy as np
import sklearn

In [ ]:
#load dataset with pandas
msrm_df=pd.read_csv('/content/drive/MyDrive/Ai-datasets/mushroom edibility classification dataset.csv')
msrm_df.head()

Unnamed: 0      class  cap-shape  ...  spore-print-color  population habitat
0           0  poisonous        5.0  ...                  2           3       5
1           1     edible        5.0  ...                  3           2       1
2           2     edible        0.0  ...                  3           2       3
3           3  poisonous        5.0  ...                  2           3       5
4           4     edible        5.0  ...                  3           0       1

[5 rows x 20 columns]

In [ ]:
msrm_df.shape

(3124, 20)

In [ ]:
#handling missing values
msrm_df.isnull().sum()

Unnamed: 0                  0
class                       0
cap-shape                   8
cap-surface                 0
cap-color                   8
bruises                     0
odor                        0
stalk-shape                 0
stalk-root                  0
stalk-surface-above-ring    0
stalk-surface-below-ring    0
stalk-color-above-ring      0
stalk-color-below-ring      0
veil-type                   0
veil-color                  0
ring-number                 0
ring-type                   0
spore-print-color           0
population                  0
habitat                     0
dtype: int64

In [ ]:
msrm_df[['cap-shape']]

cap-shape
0           5.0
1           5.0
2           0.0
3           5.0
4           5.0
...         ...
3119        5.0
3120        2.0
3121        2.0
3122        5.0
3123        5.0

[3124 rows x 1 columns]

In [ ]:
from sklearn.impute import SimpleImputer
impute = SimpleImputer(missing_values=np.nan, strategy='most_frequent')
impute.fit(msrm_df[['cap-shape']])
msrm_df['cap-shape']=impute.transform(msrm_df[['cap-shape']])


In [ ]:
msrm_df.isnull().sum()

Unnamed: 0                  0
class                       0
cap-shape                   0
cap-surface                 0
cap-color                   8
bruises                     0
odor                        0
stalk-shape                 0
stalk-root                  0
stalk-surface-above-ring    0
stalk-surface-below-ring    0
stalk-color-above-ring      0
stalk-color-below-ring      0
veil-type                   0
veil-color                  0
ring-number                 0
ring-type                   0
spore-print-color           0
population                  0
habitat                     0
dtype: int64

In [ ]:
impute.fit(msrm_df[['cap-color']])
msrm_df['cap-color']=impute.transform(msrm_df[['cap-color']])

In [ ]:
msrm_df.isnull().sum()

Unnamed: 0                  0
class                       0
cap-shape                   0
cap-surface                 0
cap-color                   0
bruises                     0
odor                        0
stalk-shape                 0
stalk-root                  0
stalk-surface-above-ring    0
stalk-surface-below-ring    0
stalk-color-above-ring      0
stalk-color-below-ring      0
veil-type                   0
veil-color                  0
ring-number                 0
ring-type                   0
spore-print-color           0
population                  0
habitat                     0
dtype: int64

In [ ]:
# Encoding categorical features
msrm_df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3124 entries, 0 to 3123
Data columns (total 20 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Unnamed: 0                3124 non-null   int64  
 1   class                     3124 non-null   object 
 2   cap-shape                 3124 non-null   float64
 3   cap-surface               3124 non-null   int64  
 4   cap-color                 3124 non-null   float64
 5   bruises                   3124 non-null   object 
 6   odor                      3124 non-null   int64  
 7   stalk-shape               3124 non-null   int64  
 8   stalk-root                3124 non-null   int64  
 9   stalk-surface-above-ring  3124 non-null   int64  
 10  stalk-surface-below-ring  3124 non-null   int64  
 11  stalk-color-above-ring    3124 non-null   int64  
 12  stalk-color-below-ring    3124 non-null   int64  
 13  veil-type                 3124 non-null   int64  
 14  veil-col

In [ ]:
msrm_df.info()

msrm_df['bruises'].unique()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3124 entries, 0 to 3123
Data columns (total 20 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Unnamed: 0                3124 non-null   int64  
 1   class                     3124 non-null   object 
 2   cap-shape                 3124 non-null   float64
 3   cap-surface               3124 non-null   int64  
 4   cap-color                 3124 non-null   float64
 5   bruises                   3124 non-null   object 
 6   odor                      3124 non-null   int64  
 7   stalk-shape               3124 non-null   int64  
 8   stalk-root                3124 non-null   int64  
 9   stalk-surface-above-ring  3124 non-null   int64  
 10  stalk-surface-below-ring  3124 non-null   int64  
 11  stalk-color-above-ring    3124 non-null   int64  
 12  stalk-color-below-ring    3124 non-null   int64  
 13  veil-type                 3124 non-null   int64  
 14  veil-col

array(['bruises is there', 'no bruises'], dtype=object)

In [ ]:
msrm_df['bruises']=msrm_df['bruises'].map({'bruises is there':1, 'no bruises':0})

In [ ]:
msrm_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3124 entries, 0 to 3123
Data columns (total 20 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Unnamed: 0                3124 non-null   int64  
 1   class                     3124 non-null   object 
 2   cap-shape                 3124 non-null   float64
 3   cap-surface               3124 non-null   int64  
 4   cap-color                 3124 non-null   float64
 5   bruises                   3124 non-null   int64  
 6   odor                      3124 non-null   int64  
 7   stalk-shape               3124 non-null   int64  
 8   stalk-root                3124 non-null   int64  
 9   stalk-surface-above-ring  3124 non-null   int64  
 10  stalk-surface-below-ring  3124 non-null   int64  
 11  stalk-color-above-ring    3124 non-null   int64  
 12  stalk-color-below-ring    3124 non-null   int64  
 13  veil-type                 3124 non-null   int64  
 14  veil-col

In [ ]:
msrm_df['ring-number'].unique()

array([1])

In [ ]:
msrm_df.drop(['ring-number'], axis=1, inplace=True)
msrm_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3124 entries, 0 to 3123
Data columns (total 19 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Unnamed: 0                3124 non-null   int64  
 1   class                     3124 non-null   object 
 2   cap-shape                 3124 non-null   float64
 3   cap-surface               3124 non-null   int64  
 4   cap-color                 3124 non-null   float64
 5   bruises                   3124 non-null   int64  
 6   odor                      3124 non-null   int64  
 7   stalk-shape               3124 non-null   int64  
 8   stalk-root                3124 non-null   int64  
 9   stalk-surface-above-ring  3124 non-null   int64  
 10  stalk-surface-below-ring  3124 non-null   int64  
 11  stalk-color-above-ring    3124 non-null   int64  
 12  stalk-color-below-ring    3124 non-null   int64  
 13  veil-type                 3124 non-null   int64  
 14  veil-col

In [ ]:
msrm_df['veil-color'].unique()

array([2])

In [ ]:
msrm_df.drop(['veil-color'], axis=1, inplace=True)
msrm_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3124 entries, 0 to 3123
Data columns (total 18 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Unnamed: 0                3124 non-null   int64  
 1   class                     3124 non-null   object 
 2   cap-shape                 3124 non-null   float64
 3   cap-surface               3124 non-null   int64  
 4   cap-color                 3124 non-null   float64
 5   bruises                   3124 non-null   int64  
 6   odor                      3124 non-null   int64  
 7   stalk-shape               3124 non-null   int64  
 8   stalk-root                3124 non-null   int64  
 9   stalk-surface-above-ring  3124 non-null   int64  
 10  stalk-surface-below-ring  3124 non-null   int64  
 11  stalk-color-above-ring    3124 non-null   int64  
 12  stalk-color-below-ring    3124 non-null   int64  
 13  veil-type                 3124 non-null   int64  
 14  ring-typ

In [ ]:
msrm_df['veil-type'].unique()

array([0])

In [ ]:
msrm_df.drop(['veil-type'], axis=1, inplace=True)
msrm_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3124 entries, 0 to 3123
Data columns (total 17 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Unnamed: 0                3124 non-null   int64  
 1   class                     3124 non-null   object 
 2   cap-shape                 3124 non-null   float64
 3   cap-surface               3124 non-null   int64  
 4   cap-color                 3124 non-null   float64
 5   bruises                   3124 non-null   int64  
 6   odor                      3124 non-null   int64  
 7   stalk-shape               3124 non-null   int64  
 8   stalk-root                3124 non-null   int64  
 9   stalk-surface-above-ring  3124 non-null   int64  
 10  stalk-surface-below-ring  3124 non-null   int64  
 11  stalk-color-above-ring    3124 non-null   int64  
 12  stalk-color-below-ring    3124 non-null   int64  
 13  ring-type                 3124 non-null   int64  
 14  spore-pr

In [ ]:
y=msrm_df[['class']]
x=msrm_df.drop(['class'], axis=1)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, random_state=1)


In [ ]:
print(X_train.shape)
print(X_test.shape)
print(msrm_df.shape)

(2343, 16)
(781, 16)
(3124, 17)


In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
scaler.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [ ]:
X_train=scaler.transform(X_train)

In [ ]:
print("per-feature minimum after scaling:\n {}".format(X_train.min(axis=0)))
print("per-feature maxmimum after scaling:\n {}".format(X_train.max(axis=0)))

per-feature minimum after scaling:
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
per-feature maxmimum after scaling:
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
